language: java

sudo: true

jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
      
before_install:
  - chmod +x mvnw

script:
  - mvn validate
  - mvn compile
  - mvn test -B
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      mvn package;
    fi
