language: java
jdk: oraclejdk11
before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      - 209322@edu.p.lodz.pl
      - 209410@edu.p.lodz.pl
      - 209412@edu.p.lodz.pl
      - 209457@edu.p.lodz.pl
    on_success: never
    on_failure: always

script:
  - mvn validate
  - mvn compile
  - mvn test -B
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      mvn package;
    fi

before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@noreply.github.com"
  - export GIT_TAG=$TRAVIS_BRANCH-v$MAJOR_VERSION.$MINOR_VERSION.$TRAVIS_BUILD_NUMBER
  - git tag -a $GIT_TAG -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  on:
    repo: IIS-ZPI/ZPI_2019_Dzienni_IO4_jamniki
    branches:
      only:
        - master
  body: "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
